### ISSUE TITLE
CTO you'd fall in love with

### ISSUE THREAD

**Issue by peppierre** [budapestjs/meetup#10]
# Topic
Due to irrealistic expectations he had, former CTO (Mr. R. C. Martin) fired and here's a new guy on the stage, the new CTO of our company. Who is one of us. Who knows developers' points of views and daily problems. Who wears clothes like simple developers wear.

And who has new and revised expectations...

# Goal
Goal is to highlight the fact that the way how we, developers act daily and the attitudes we have must be changed very soon.
In this talk, there is nothing front-end related, it's rather about common things in software development.

## Details

Estimated length in minutes: 60 mins

## Presenter

Peter Abraham @ Accenture

**Comment by tiborsaas** [comment]
I'd rather favor hard-core dev talks limited to 20 mins.

**Comment by gergob** [comment]
I like these kind of talks, but yeah I think if we can fit in the 20-30 mins time-frame thats good :)

**Comment by peppierre** [comment]
ok. let's keep it in bucket and see whather in the future it worth to be picked.

**Comment by gs00s** [comment]
@peppierre Robert C. Martin who wrote Clean Code?

**Comment by peppierre** [comment]
@blacksonic yes exactly. ;)

**Comment by snorbi07** [comment]
https://www.meetup.com/budapest-js/events/241784279/
