### ISSUE TITLE
Shake it till you make it (with Webpack)

### ISSUE THREAD

**Issue by sonicoder86** [budapestjs/meetup#11]
# Topic

With the second version of Webpack tree-shaking has become available to it's users. Due to the different method how Webpack accomplishes it in contrary to Rollup, it makes a bit more complicated to achieve proper tree-shaking. I would show how Webpack's tree-shaking works under the hood, what pitfalls it has and how to overcome them.

# Goal

The goal is to explain how tree-shaking works and with this knowledge make existing build pipelines more effective.

**Comment by snorbi07** [comment]
+1! Seems like a very cool topic. Just the other day I was reading up on what are the differences between the 2.
Would you be able to prepare it for the June meetup?

**Comment by gs00s** [comment]
Yes, June would be fine.
This week I'll publish a blog post regarding the topic, will link it here to give a deeper insight.
