### ISSUE TITLE
Boomla: a simple, powerful application platform for websites

### ISSUE THREAD

**Issue by zupa-hu** [budapestjs/meetup#24]
# Topic
Boomla: a simple, powerful application platform for websites

# Description
Boomla was designed to dramatically reduce the complexity of web development. The complexity is not so much inherent in the problem, but existing solutions: frameworks. To build a simple solution, we have to focus on getting rid of outdated ideas. Frameworks only add, it's platforms, that remove, thus simplify. We have to throw out the entire stack, starting with the filesystem, and rebuild it from scratch. Come and discover a platform seemingly from a different universe.

# Details
Estimated length: 50-60min without questions

# Presenter
Tibor Halter @ Boomla

**Comment by snorbi07** [comment]
Hi @zupa-hu,
Thanks for the submission! We'll get back to you with the possible dates.

**Comment by zupa-hu** [comment]
Great, thanks!

**Comment by snorbi07** [comment]
Hi @zupa-hu,
June 21st would be the date of the next meetup. Would that date work for you?

We would request 2 things. Please limit your presentation to 40-45 minutes. Also, would you be so kind to provide a bit more concrete information in your abstract. "Yet another framework" is common in the JS community, so usually people are skeptical about the bold claims of each framework, thus it would be wise to give some concrete incentive to participate.

**Comment by zupa-hu** [comment]
Hi @snorbi07, the date is perfect. Let me get back on the other 2.

**Comment by zupa-hu** [comment]
Hi @snorbi07,
thanks for throwing it back, it was a good point. Here is Abstract v2. Thoughts?

# Topic
Boomla Website OS intro

# Description
Boomla is a virtual OS from scratch designed to simplify building websites - and web applications in general. Currently, it runs JavaScript only. It provides a transactional, version controlled FS which doubles as a DB. Enjoy undo for your entire FS. It is serverless, built for high concurrency & scalability, yet it comes with a sync interface for simple programming. Built-in webserver. Apps run in isolated transactions. Share and install packages (apps). Forget Linux quirks, processes, complex deployments, system orchestration, sysadmin work, locking issues. Write less code. Oh, and it's blazing fast. Come and discover a platform seemingly from a different universe.

**Comment by snorbi07** [comment]
Perfect! Thanks! We'll announce the meetup in the coming days on meetup.com as well

**Comment by zupa-hu** [comment]
Great, thanks a lot!
