### ISSUE TITLE
Building Native apps with Titanium

### ISSUE THREAD

**Issue by Topener** [budapestjs/meetup#25]
# Topic
Building native apps with the JavaScript framework Titanium

# Description
You don't have to learn objective-c and java to build apps (nor kotlin/swift for that matter), you can use your existing knowledge to build apps with JavaScript using the Titanium SDK and its Alloy MVC framework.

In my talk I'll very quickly tell you what Titanium is, and from there I'll walk you through a few typical scenarios you might encounter when building apps.

**Comment by snorbi07** [comment]
Thanks for the topic @Topener. What would be a suitable time for you to do the presentation?

As a for your information... for the June meetup, most likely we are set. The next one will be in September (after the summer break), where we are most likely fully booked (not yet confirmed).

**Comment by Topener** [comment]
Hi @snorbi07! 

June won't work for me so September would be the first possible for me. After that I'm also good, I have nothing planned yet.
fyi, I'm not local, but I'll be flying there for the meetup!

**Comment by snorbi07** [comment]
Thanks, we appreciate that you would put in an extra effort (besides the presentation itself) to educate the local JS community!
We'll get a response about the September event in the middle of the summer (latest end of July) and afterwards I can propose some dates for you.

**Comment by Topener** [comment]
Sounds great! Let me know

**Comment by Topener** [comment]
@snorbi07 hi there! Any update on this?

**Comment by snorbi07** [comment]
Hi @Topener,
Thanks for pinging me! There is a free slot for the September 20th meetup if you are interested.

**Comment by Topener** [comment]
Hi! I'm afraid I have something on the 21st in the Netherlands... so that won't work out. Perhaps October?

**Comment by snorbi07** [comment]
Would October 18th work for you?

**Comment by Topener** [comment]
@snorbi07 yep that would work for me!

**Comment by benestudiojobs** [comment]
Hi there! As to fix, one speaker will be brought by Bene Studio - our developer Essam Tarik from Egypt will cover a topic around React/React Native - more details soon. Thanks :)

**Comment by snorbi07** [comment]
@benestudiojobs, please open a separate GitHub issue for that. This is about @Topener's talk and not generally the October 18th meetup. Thanks!
