### ISSUE TITLE
React state management with Rematch

### ISSUE THREAD

**Issue by koss-lebedev** [budapestjs/meetup#26]
### Topic

React state management with Rematch

### Description

State management is a hot topic, with a lot of libraries trying to tackle the problem in their unique way.  Redux seems to have taken a strong lead, with a huge community behind it and great documentation. But is there a way to do even better? Can we improve on Redux ideas to make developer experience better? In this talk, we’ll talk about Rematch, a state management library that strives to push Redux to the next level.

**Comment by snorbi07** [comment]
Hi @koss-lebedev, 
Thanks for the submission.  The next meetup is scheduled for September 20th. Would that time slot work for you?

**Comment by koss-lebedev** [comment]
Hey @snorbi07!
definitely, 20th is great 👍

**Comment by snorbi07** [comment]
Would you be so kind to contact us (budapestjs org) on meetup.com with a short Bio? Also, is 20-30 minutes enough for your talk?

**Comment by koss-lebedev** [comment]
yes, I think 30 minutes should be enough for a talk and a quick Q&A if people want to ask some follow-up questions. I'll send you a message on meetup.com in a few minutes

**Comment by snorbi07** [comment]
Meetup event: https://www.meetup.com/budapest-js/events/253746571/
