### ISSUE TITLE
React + Flow: Dive in

### ISSUE THREAD

**Issue by Zaggen** [budapestjs/meetup#27]
All programmers have a special part of our brains exclusively dedicated to introduce bugs in our apps, even if we don’t like to admit it, we make typos, pass wrong data and return unicorns where a number was expected. So relying on a static analysis tool like Flow to keep an eye on our code, will not only help us avoid having those issues, but more importantly by doing so we’ll look smarter. This talk will take you to some of the basics and relevance of the type system and then dive deep into typing a react app.

**Comment by snorbi07** [comment]
Hi @Zaggen,

First and foremost, sorry for the delayed response. Thank you for the submission, looks great!
When would you like to present this topic? Would September work for example?

**Comment by Zaggen** [comment]
Hey @snorbi07, don't worry, September sounds good, do you have some specific day of the month & week for all meetups or we'll just come up with something that works for both?

**Comment by snorbi07** [comment]
Usually we go with the 3rd Thursday of the month (20th of September in this particular case), however we are open to shifting that if it doesn't work for you

**Comment by Zaggen** [comment]
September 20th works for me :)

**Comment by snorbi07** [comment]
Awesome! We can discuss the details on Meetup.com chat part. For one thing, we would need your real name and a bit of background that we can add to the meetup event. Just so the audience knows who is talking to them :)

**Comment by snorbi07** [comment]
Hi @Zaggen, still waiting for your message ;)

**Comment by Zaggen** [comment]
Hey @snorbi07 , sorry I just noticed you replied the same day. I will write you on meetup.com

**Comment by Zaggen** [comment]
@snorbi07 Spam filter there is not letting me send anything, no matter what I write, can you try to ping me here https://www.meetup.com/members/260571765/ ?

**Comment by snorbi07** [comment]
Meetup event: https://www.meetup.com/budapest-js/events/253746571/
