### ISSUE TITLE
Talk proposal: JavaScript Closer to the Metal (2015. january)

### ISSUE THREAD

**Issue by flaki** [budapestjs/meetup#3]
# Title

**JavaScript closer to the metal**
# Description

Early days alert & scrolling titlebars' JavaScript has gone a long way. Through standardization (EcmaScript) and widespread use it has made its way to virtually every digital device of the new millenia.
Through this long journey the [IoT](http://en.wikipedia.org/wiki/IoT) slowly seems to transcend into a world of JoT (JavaScript of Things).

After a brief introduction to the journey we will have a sneak peek into how JavaScript is starting to conquer the hardware & embedded landscape — previously reserved for systems languages closer to the metal.
# Draft
### How it all started: _JavaScript growing up_
- the first lower-level DOM-APIs + standardization (EcmaScript)
- i.e. `Geolocation`, `Battery API`
#### JavaScript conquering the frontend, backend\* & apps
- `node.js`: filesystem access, low-level network access, etc...
- single-page apps
- packaged webview-apps

_\* and the commandline_
### JoT - _JavaScript of Things**_

JS on Arduino & dedicated hardware based on JavaScript (i.e.: Tessel)
accessing & programming all kinds of hardware via simple JS interfaces.*

_(\* possible TESSEL demo driving the [dig-ole OLED matrix display](http://www.digole.com/index.php?productID=540))_

![Tessel OLED](https://pbs.twimg.com/media/B6Bj3yvIQAE61fY.jpg)
### Accessible & affordable JS devices, apps & IoT:
- Firefox OS and Jan OS  
- **Firefox OS** introducing JS hardware bindings for small embedded systems (they call these _mobile phone_s ;) )
- **Jan OS** giving the above thing to your own hands w/ hackable hardware & a simple JS command(line)!

![Jan OS](http://image.slidesharecdn.com/jsconfeu2014-140913105525-phpapp01/95/abusing-phones-to-make-the-internet-of-things-jsconf-eu-2014-45-638.jpg?cb=1410706456)
### BONUS!

Low level API-s do not stop at mobile/IoT/hardware!
### [The Extensible Web is at our doorsteps!](https://extensiblewebreportcard.org/)

`Object.observe`, `Service Workers`, `Audio API`, `WebAnimations` were just the begining — giving low-level functionality into the hands of web developers will change the web-as-we-know-it FUNDAMENTALLY!  
_(coming soon to a browser near you: sensors, hardware, webcrypto, event loop handling, codecs & more!)_

**Comment by gergelyke** [comment]
:+1:

**Comment by turbo5** [comment]
nice!
