### ISSUE TITLE
Building a JAMStack website with Angular+Scully

### ISSUE THREAD

**Issue by BlindDespair** [budapestjs/meetup#31]
### Description
In the talk I would like to present a sushi ordering website built from scratch using Angular and Scully (a cutting edge new JAMStack framework made for Angular). While Scully is still in alpha at the time of writing this abstract, I am already excited to share my experiences of working with and what it has to offer so far. I would also cover what it took me to create such a setup in a bigger picture and why such decisions were made.

**Comment by snorbi07** [comment]
Hi @BlindDespair, thanks for the submission! As discussed, we'll schedule your talk for the [April meetup.](https://www.meetup.com/budapest-js/events/266462479/)
