### ISSUE TITLE
~~New~~ Old way to write CSS, but with better DX

### ISSUE THREAD

**Issue by levchak0910** [budapestjs/meetup#39]
## Description
In this talk, we will review the current state of formatting and linting tools that ensure consistent CSS code style in Vue single file components (SFC). We will go through several pain points and learn how to gradually improve our code, using appropriate tool for each step.

## Details
Estimated length: 40-50 minutes

## Presentor
Levcsák Sándor
Senior front-end developer, passionate about Vue and its ecosystem, highly interested in SSR applications and DX tools.
Linkedin: https://www.linkedin.com/in/levchak0910
Github: https://www.github.com/levchak0910

**Comment by snorbi07** [comment]
Hi @levchak0910,

Thanks for submitting a talk!

We would have a JSConf kick-off meetup on the 26th of June where you could do your talk. One requirement is that it would be good to fit the talk into 20minutes, 25 at most. Would that work for you?

**Comment by levchak0910** [comment]
Hi @snorbi07 
~~Thanks for the suggestion, but unfortunately, it will not work (~~
~~I have a lot of content and cutting it out would not make my talk complete~~
I reviewed my presentation, cut all interactions with the audience, and reduced the demo time, so now I can fit into 20-25 minutes
Would be happy to preset it )

**Comment by snorbi07** [comment]
@levchak0910  Thank you very much. The event has been announced and I will add your talk to the list!

**Comment by snorbi07** [comment]
Event: https://www.meetup.com/budapest-js/events/301717241/

**Comment by levchak0910** [comment]
Is it possible to mark `New` in the title as `text-decoration: line-through;`?

**Comment by snorbi07** [comment]
Unfortunately it is not possible. Meetup is very limited in this regard.
![Screenshot_2024-06-19_13-50-32](https://github.com/budapestjs/meetup/assets/3918033/ba4bb684-9520-4c5a-8413-7b7fcf82e1f8)

**Comment by levchak0910** [comment]
I see. Ok, not problem at all. Thanks

**Comment by levchak0910** [comment]
Delivered )
https://levchak0910.github.io/talk-vue-css-dx
Thank you @snorbi07
