### ISSUE TITLE
Hypeless JavaScript development

### ISSUE THREAD

**Issue by snorbi07** [budapestjs/meetup#5]
## Topic

Experiences and input related to large scale JavaScript development.

## Description
This presentation will not be about your latest JavaScript framework. Instead, it will give you an overview of AdNovum's largest and longest running JavaScript based project. Over the last 7 years we've been developing the mobile banking application of one of the world's largest financial organizations. You will learn about the decisions we made, the technologies used in the project and how we manage to keep developing the application at a high pace to keep it one of the highest rated mobile banking apps.

**Comment by p-boon** [comment]
Thank you for the invitation!

**Comment by snorbi07** [comment]
Thanks for agreeing to do this presentation ;)

**Comment by gs00s** [comment]
It looks cool, if this isn't an against transpiler and frameworks talk. Just came to my mind because of the word hypeless.

**Comment by snorbi07** [comment]
@blacksonic, it isn't about that... and if yes, you cannot have an opinion that differs? IMO we should filter for valuable content and not censor opinions.

**Comment by gs00s** [comment]
Then big up for the talk :)

@snorbi07 Don't want to censor other opinions, just avoid Javascript Fatigue like talks...most of them are bashing existing tooling but don't offer solutions...i feel them non inclusive.
